# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.1.dev1+gaf2c0c3.d20230102'
__version_tuple__ = version_tuple = (1, 0, 1, 'dev1', 'gaf2c0c3.d20230102')
