name: pull_request

on:
  pull_request:
    branches:
    - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: make install
    - name: Run linters
      run: make lint
    - name: Run mypy
      run: make mypy
    - name: Run tests
      run: make test

  license_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dump all package's dependencies
      run: |
        make install-package
        pip freeze > requirements.dump.txt
    - name: Check Python deps licenses
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v0.8.0
      with:
        requirements: 'requirements.dump.txt'
        fail: 'StrongCopyleft,NetworkCopyleft,Other,Error'
        totals: true
        headers: true
    - name: Print report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}"
