name: pull_request

on:
  pull_request:
    branches:
    - "*"

jobs:
  lint_and_test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linters
      run: make lint
    - name: Run mypy
      run: make mypy
    - name: Run tests
      run: make test

  license_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Check Python deps licenses
      id: license_check_report
      uses: pilosus/action-pip-license-checker@2c70e13466d79c8f0e9e9874a50db9ca44bb6502
      with:
        requirements: 'requirements.txt,requirements.github.txt'
        fail: 'Copyleft'
        exclude: 'pylint'
        with-totals: true
        table-headers: true
        github-token: ${{ secrets.OAUTH_TOKEN_GITHUB }}
        verbose: true
    - name: Print report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}"
